### PR TITLE
 Adding id and class attribute to elements through the interface HtmlSelector

### PR DESCRIPTION
**Pull request by kenji-getpowered**
Hi,

What do you think about this little modification.

Class and id are very useful to manipulate elements with CSS and javascript.

### CODE REVIEW

**Comment by fmcarvalho** [comment]
I liked your proposal. But I have some enhancements to suggest to you. Tomorrow I will give you detailed feedback. Thanks

**Comment by kenji-getpowered** [comment]
Ok show me,

Actually while I looked back at my modifications, I reworked the project a little bit yesterday to handle attributes with a generic way.

**Comment by kenji-getpowered** [comment]
Hello, 

The second thing I am trying to do right now is to find a generic way to have attributes with the fluent style.

It could be written like this :

headerRow.th().a().class("link").id("gnaLink").href("http://gnagna.com").text("text towards link");

**** NEW package ******
htmlflow.attributes
AttrClass
AttrHref
AttrId
HtmlAttribute
HtmlAttributeAbstract

But I am struggling with genericity 
```java
public abstract class HtmlWriterComposite<T, U extends HtmlWriterComposite<T,U>> implements HtmlWriter<T>, HtmlSelector<HtmlWriterComposite<T, U>> {

    private final AttrId<U> attrId = new AttrId<U>();

    public U id(String href){attrId.setValue(href);return this;} <-- incompatible types expected U, found :HtmlWriterComposite<T,U> 
```

**Comment by fmcarvalho** [comment]
Instead of:

       implements ..., HtmlSelector<HtmlWriterComposite<T, U>>

Shouldn't it be:

        implements ..., HtmlSelector<U>
?
       
Regarding my thoughts I was planning the two simple suggestions:

* I think that setClassAttribute method could have a shorter name with just one word, such as, className(...) or attribClass(...)

* The HtmlSingleElement should also share this same feature -- the capacity to define its class and id attributes.

Finally, with this new feature we must replicate the following instruction by all concrete elements:

       out.println("<div"+getClassAttribute()+getClassAttribute()+">");

We should find some way of avoiding this repetition among all elements. Maybe the methods doWriteBefore and doWriteAfter should disappear. The base class of all elements could store the tag of the derived element, and then the write() method could do all the job. What do you think?

In this case some elements, such as the HtmlForm that currently are including its attributes through the doWriteBefore, should also use the same base storage to hold the other attributes. In their instantiation they could provide to base constructor, the tag and the attributes. 

Maybe we should have an AbstractHtmlWriter that is the base class for the composite and the HtmlSingleElement.

**Comment by kenji-getpowered** [comment]
About my idea about genericity, I think it's too much for my needs at this time. 

About replication of code, yes there is redundancy at this specific point, 

the difficulty for having a generic do writeXXX methods is about handling the depth.
How to handle the difference between :
'''java
	@Override
	public void doWriteBefore(PrintStream out,  int depth) {
		tabs(depth);
		out.println("<body>");
		tabs(++depth);
	}
'''
and
'''java
// htmlflow.elements.HtmlDiv<T>
	@Override
	public void doWriteBefore(PrintStream out, int depth) {
		out.println("<div"+getClassAttribute()+getIdAttribute()+">");
		tabs(depth+1);
	}

	@Override
	public void doWriteAfter(PrintStream out, int depth) {
		out.println();
		tabs(depth);
		out.println("</div>");
	}
''' 
or 
'''java
// htmlflow.elements.HtmlForm<T>
// why 2 depths at this point?
	@Override
	public void doWriteAfter(PrintStream out, int depth) {
		out.println("");
		tabs(depth);
		out.println("</form>");
		tabs(depth);
	}
'''

otherwise of course we might have a generic method.

About 
'''
   implements ..., HtmlSelector<HtmlWriterComposite<T, U>>
'''
It is because I want 


'''    @Override
    public HtmlWriterComposite<T> classAttr(String classAttribute) {
        this.classAttribute = classAttribute;
        return this;
    }
'''

to return itself.

**Comment by kenji-getpowered** [comment]
I have made a lot of changes :

> I think that setClassAttribute method could have a shorter name with just one word, such as, className(...) or attribClass(...) :+1: 


>We should find some way of avoiding this repetition among all elements. Maybe the methods doWriteBefore and doWriteAfter should disappear. The base class of all elements could store the tag of the derived element, and then the write() method could do all the job. What do you think? :+1: 

I have tried first to move up those methods doWriteBefore and doWriteAfter into the HtmlWriterComposite so the maximum of code will be at the same place. It will be easier to manage them. The difficulty is to handle *hierarchy* when printing
 
'''
     public void doWriteBefore(PrintStream out, int depth) {
       tabs(depth);
       out.print(getElementValue());
     }

        
    public void doWriteAfter(PrintStream out, int depth, boolean doTab) {
        // RMK : do not insert tabs after a text node
        if(doTab){
          tabs(depth);
        }
        out.println("</"+ getElementName()+">");
    }
    
    protected String getElementValue() {
      return  "<"+ getElementName()+getClassAttribute()+getIdAttribute()+">";
     }
'''
Now I have the following output : (check unit tests on my branch if you want to see)

'''html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" >
		<head>
			<title>Task Details</title>
		</head>
		<body>
			<h0>Task Details</h0>
			<hr/>
			<div>Id: 1				<br/>
Title: Unit Test				<br/>
Description: Test of element name				<br/>
Priority: High</div>
		</body>
</html>
'''

**Comment by fmcarvalho** [comment]
I agree with your last changes and I think that I have an alternative to provide a fluent idiom that enables to write:

```java
headerRow.th().classAttr("link").idAttr("gnaLink").href("http://gnagna.com").text("text towards link");
````
To that end, you must declare `HtmlWriterComposite` as:

```java
HtmlWriterComposite<T, U extends HtmlWriterComposite> implements HtmlWriter<T>, HtmlSelector<U>
```
And  the `classAttr` method must be implemented as :
```java
    public U classAttr(String classAttribute) {
        this.classAttribute = classAttribute;
        return (U)this;
    }
    // as well for idAttr method
```

And then any derived class must define its own class as the second type argument, such as:
```java
class HtmlForm<T> extends HtmlWriterComposite<T, HtmlForm>
```

I think this way you can solve all the requirements, including a generic way to have attributes with the fluent style.

**Comment by kenji-getpowered** [comment]
Good idea about the fluent style for genericity!

I applied it to the code I already add and it works! see the commit I just did.

I can make them even more generic and I can remove code such as 
```
	@Override
	public void write(int depth, Object model) {
		out.print("<link rel=\"Stylesheet\" type=\"text/css\" href=\"" + href + "\"/>");
		tabs(depth);
	}
```
having 3 attributes (rel, type and href) and a single write method that parses attributes to generate the tag.

**Comment by fmcarvalho** [comment]
Yes, it looks consistent with your approach to other attributes. It is fine for me.

**Comment by kenji-getpowered** [comment]
Hi again, maybe you can help me.

I have  a new struggle with generics again.

please take a look at my branche attribute from the fork :
https://github.com/kenji-getpowered/HtmlFlow/tree/attribute


htmlflow.elements.HtmlDivTest.testIdAndClassAttribute() 
Line 73

```java 
      taskView.head().scriptLink("test.css");
    taskView.body()
    .div()
      .classAttr(divClass) // after addAttr() I have a HtmlDiv
      .idAttr(divId)
      .addAttr("toto", "tutu").form("/action.do"); // after addAttr() I have a HtmlWriterComposite ==> compilation ERROR
//    .div()
//    .classAttr(divClass)
//    .form("/action.do")
```

Can you see why?

**Comment by fmcarvalho** [comment]
That is very strange!!!! Because if you split it in various statements, it will work:

```java
    HtmlDiv<Task> d = taskView.body().div();
    d = d.classAttr(divClass);
    d = d.idAttr(divId);
    d = d.addAttr("toto", "tutu");
    d.form("/action.do");
```
And again the following gives an error:
```java
d = d.classAttr(divClass).idAttr(divId);
```

But like this just works again:
```
d = d.classAttr(divClass);
d = d.idAttr(divId);
```

I don’t get it. But I will keep looking for the reason. I will give you news soon…

**Comment by fmcarvalho** [comment]
@kenji-getpowered I found it. instead of:

```java
public class HtmlDiv<T> extends HtmlWriterComposite<T, HtmlDiv> 
```

You must declare it as:
```java
public class HtmlDiv<T> extends HtmlWriterComposite<T, HtmlDiv<T>> 
```

In truth you must do it for all concrete elements.

**Pull request merged**
